# -*- coding: utf-8 -*-
"""Untitled62.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14G5SHsbz-KLIgSMYB1UL702jbUGPC8iC
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install spotipy transformers

# Commented out IPython magic to ensure Python compatibility.
# %pip install python-dotenv

import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from transformers import pipeline

# Spotify API credentials
SPOTIFY_CLIENT_ID = "your_client_id"
SPOTIFY_CLIENT_SECRET = "your_client_secret"

sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(
    client_id=SPOTIFY_CLIENT_ID,
    client_secret=SPOTIFY_CLIENT_SECRET
))

# Emotion detection pipeline
emotion_pipeline = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base", return_all_scores=True)

# Get user mood input
user_text = input("🧠 How are you feeling today?\n→ ")

# Detect emotion from text
def detect_emotion(text):
    result = emotion_pipeline(text)[0]
    top = sorted(result, key=lambda x: x['score'], reverse=True)[0]['label']
    return top

emotion = detect_emotion(user_text)
print(f"\n🎯 Detected Mood: {emotion}")

# Language selection
languages = {
    "1": "Hindi",
    "2": "Telugu",
    "3": "Tamil",
    "4": "Kannada",
    "5": "Malayalam",
    "6": "Punjabi"
}

print("\n🎬 Choose your movie song language:")
for key, lang in languages.items():
    print(f"{key}. {lang}")

choice = input("Enter choice (1-6): ")
language = languages.get(choice, "Hindi")
print(f"\n🎼 Selected Language: {language}")

# Build query based on mood and language
def get_language_mood_query(emotion, language):
    mood_keywords = {
        "joy": "happy",
        "love": "romantic",
        "sadness": "sad",
        "grief": "emotional",
        "anger": "intense",
        "annoyance": "breakup",
        "calm": "chill",
        "neutrality": "lofi",
        "excitement": "party"
    }
    mood = mood_keywords.get(emotion, "mood")
    return f"{mood} {language.lower()}"

query = get_language_mood_query(emotion, language)

# Search Spotify for relevant songs
def search_mood_movie_songs(query):
    results = sp.search(q=query, type='track', limit=8)
    if not results['tracks']['items']:
        return ["❌ No songs found."]
    return [
        f"🎵 {track['name']} by {track['artists'][0]['name']}\n▶️ {track['external_urls']['spotify']}"
        for track in results['tracks']['items']
    ]

# Display recommendations
print(f"\n🔍 Showing results for: '{query.title()}' songs\n")
songs = search_mood_movie_songs(query)
for song in songs:
    print(song, "\n")

